### PR TITLE
Add UWP support

### PR DESCRIPTION
**Pull request by TastesLikeTurkey**
This adds a UWP project. I'm not sure how to do all the Nuget stuff, but it gets a basic, working project there.

### CODE REVIEW

**Comment by baynezy** [comment]
@RareNCool - thank you. I have a few questions regarding this.

1. What of the original project did not work with UWP? Can you not include it from NuGet as a dependency on what you are trying to do?
1. Why have you needed to copy classes from the existing project?

**Comment by RareNCool** [comment]
@baynezy
> What of the original project did not work with UWP? Can you not include it from NuGet as a dependency on what you are trying to do?

Mainly the file-conversion. The APIs used aren't supported by UWP. Installation from Nuget just fails.

> Why have you needed to copy classes from the existing project?

In hindsight, that was a mistake. Referencing the existing project won't work, but I should have created a PCL with the shared classes. It was mostly just a quick way of getting it working in the project I'm working on. I'll try to fix that tonight.

**Comment by baynezy** [comment]
I have started #53 which will encompass this. So I am going to close this ticket.

**Comment by baynezy** [comment]
@TastesLikeTurkey - #53 is now complete and version 3.x has been published on NuGet. So should work with UWP projects now.

**Pull request closed without merging**
