### PR TITLE
fix whitespace clearing for unix

### PR DESCRIPTION
**Pull request by laocane**
fix whitespace clear for unix

### CODE REVIEW

**Comment by baynezy** [comment]
@laocane - thanks for your contribution. Can you please add some test cases to highlight what you are trying to resolve?

If you want to see what I mean please look at the [tests I added](https://github.com/baynezy/Html2Markdown/pull/221/files) to your other contribution.

**Comment by laocane** [comment]
sure, I'll add some unit tests by the end of this week

Kindest regards, Adam.

**Comment by baynezy** [comment]
@laocane - can you please test the latest `develop` please? I feel I may have resolved all of the Linux issues. Let me know if I have not.

**Comment by laocane** [comment]
I will test the latest develop this weekend and let you know.

Kindest regards

**Comment by laocane** [comment]
just tested on a linux docker container and it seems to be working fine

closing this PR

**Pull request closed without merging**
