### PR TITLE
Shift to .Net Standard 1.4

### PR DESCRIPTION
**Pull request by Tlaster**
.Net Standard 1.4 is a more common way to build up a library nowadays, it support more platform than the .Net Framework 4.5
In order to shift to .Net Standard 1.4, I change the HtmlAgilityPack to AngleSharp since the HtmlAgilityPack doesn't support .Net Standard 1.4

### CODE REVIEW

**Comment by baynezy** [comment]
@Tlaster - thanks for this. I will take a look at it. This PR has [broken my build](https://ci.appveyor.com/project/baynezy/html2markdown/build/1.0.150) so I need to work out what needs to change to get it working again.

**Comment by mitchcapper** [comment]
Another option is to switch to using HtmlAgilityPack.NetCore a net core port of HtmlAgilityPack

**Comment by baynezy** [comment]
I am working on #53 which will incorporate this. So I am going to close it.

**Comment by baynezy** [comment]
@Tlaster and @mitchcapper #53 is not complete and the 3.x version is now published to NuGet. This is a .Net standard 1.4 compatible version.

**Pull request closed without merging**
